import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Users,Tags,ArrowLeftRight,LayoutDashboard,Plus,Search,Trash2,Edit3,RotateCcw,LibraryBig,AlertCircle,CheckCircle2,Menu,X} from 'lucide-react';
import './styles.css';

const API='http://localhost:8080/api';
async function api(path,options={}){
  const res=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  const text=await res.text(); let data=null; try{data=text?JSON.parse(text):null}catch{}
  if(!res.ok){const msg=data?.message || Object.values(data?.messages||{})[0] || data?.error || `Request failed (${res.status})`; throw new Error(msg)}
  return data;
}
const emptyBook={title:'',author:'',isbn:'',categoryId:'',quantity:''};
const emptyMember={name:'',email:'',phone:'',address:''};
const emptyCategory={name:''};
const today=()=>new Date().toISOString().slice(0,10);
function App(){
 const [page,setPage]=useState('dashboard'),[books,setBooks]=useState([]),[members,setMembers]=useState([]),[categories,setCategories]=useState([]),[borrowings,setBorrowings]=useState([]),[loading,setLoading]=useState(true),[toast,setToast]=useState(null),[mobile,setMobile]=useState(false);
 const load=async()=>{setLoading(true);try{const [b,m,c,br]=await Promise.all([api('/books'),api('/members'),api('/categories'),api('/borrowings')]);setBooks(b);setMembers(m);setCategories(c);setBorrowings(br)}catch(e){notify(e.message,'error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]); useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),3500);return()=>clearTimeout(t)}},[toast]);
 const notify=(message,type='success')=>setToast({message,type});
 const nav=(p)=>{setPage(p);setMobile(false)};
 const active=borrowings.filter(x=>x.status==='ISSUED').length, totalFine=borrowings.reduce((s,x)=>s+Number(x.fine||0),0);
 const names={books:'Books',members:'Members',categories:'Categories',borrowings:'Borrowings',dashboard:'Dashboard'};
 return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="logo"><LibraryBig size={22}/></div><div><strong>Libra</strong><span>Library Manager</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{[['dashboard',LayoutDashboard],['books',BookOpen],['members',Users],['categories',Tags],['borrowings',ArrowLeftRight]].map(([id,Icon])=><button className={page===id?'nav active':'nav'} key={id} onClick={()=>nav(id)}><Icon size={19}/>{names[id]}</button>)}</nav><div className="sideFoot">Spring Boot API<br/><span>localhost:8080</span></div></aside><main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{names[page]}</h1><p>Manage your library from one place.</p></div><button className="refresh" onClick={load}><RotateCcw size={17}/> Refresh</button></header>{loading?<div className="loading">Loading library data…</div>:<>{page==='dashboard'&&<Dashboard books={books} members={members} categories={categories} borrowings={borrowings} totalFine={totalFine} onNav={nav}/>} {page==='books'&&<Books books={books} categories={categories} refresh={load} notify={notify}/>} {page==='members'&&<Members members={members} refresh={load} notify={notify}/>} {page==='categories'&&<Categories categories={categories} refresh={load} notify={notify}/>} {page==='borrowings'&&<Borrowings books={books} members={members} borrowings={borrowings} refresh={load} notify={notify}/>}</>}</main>{toast&&<div className={'toast '+toast.type}>{toast.type==='success'?<CheckCircle2 size={18}/>:<AlertCircle size={18}/>} {toast.message}</div>}</div>
}
function Dashboard({books,members,categories,borrowings,totalFine,onNav}){const available=books.reduce((s,b)=>s+Number(b.availableQuantity||0),0);return <section><div className="hero"><div><span className="eyebrow">LIBRARY OVERVIEW</span><h2>Everything your library needs.</h2><p>Track inventory, members and lending activity with a clean workflow.</p></div><button onClick={()=>onNav('borrowings')} className="primary"><Plus size={18}/> Issue a book</button></div><div className="stats">{[[BookOpen,'Total Books',books.length], [Users,'Members',members.length],[ArrowLeftRight,'Active Issues',borrowings.filter(x=>x.status==='ISSUED').length],[Tags,'Available Copies',available]].map(([I,l,v])=><div className="stat" key={l}><div className="statIcon"><I size={20}/></div><div><span>{l}</span><b>{v}</b></div></div>)}</div><div className="grid2"><div className="panel"><div className="panelHead"><h3>Recent borrowings</h3><button onClick={()=>onNav('borrowings')} className="textBtn">View all</button></div>{borrowings.slice(-5).reverse().map(x=><div className="activity" key={x.id}><div className="avatar">{x.status==='ISSUED'?'↗':'✓'}</div><div><b>Book #{x.bookId}</b><span>Member #{x.memberId} · {x.issueDate}</span></div><Status value={x.status}/></div>)}{!borrowings.length&&<Empty text="No borrowing records yet."/>}</div><div className="panel"><div className="panelHead"><h3>Library snapshot</h3></div><div className="snapshot"><div><span>Categories</span><b>{categories.length}</b></div><div><span>Available copies</span><b>{available}</b></div><div><span>Total fines</span><b>₹{totalFine.toFixed(2)}</b></div></div></div></div></section>}
function Books({books,categories,refresh,notify}){const [q,setQ]=useState(''),[edit,setEdit]=useState(null),[form,setForm]=useState(emptyBook),[show,setShow]=useState(false);const rows=books.filter(b=>(b.title+' '+b.author+' '+b.isbn).toLowerCase().includes(q.toLowerCase()));const submit=async e=>{e.preventDefault();try{const body={title:form.title,author:form.author,isbn:form.isbn,categoryId:form.categoryId?Number(form.categoryId):null,quantity:Number(form.quantity)};if(edit)await api('/books/'+edit,{method:'PUT',body:JSON.stringify(body)});else await api('/books',{method:'POST',body:JSON.stringify(body)});notify(edit?'Book updated':'Book added');setShow(false);setEdit(null);setForm(emptyBook);refresh()}catch(e){notify(e.message,'error')}};const del=async id=>{if(!confirm('Delete this book?'))return;try{await api('/books/'+id,{method:'DELETE'});notify('Book deleted');refresh()}catch(e){notify(e.message,'error')}};return <section><Toolbar q={q} setQ={setQ} action={()=>{setShow(true);setEdit(null);setForm(emptyBook)}} label="Add book"/><div className="tableWrap"><table><thead><tr><th>Book</th><th>ISBN</th><th>Category</th><th>Stock</th><th>Available</th><th></th></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td><b>{b.title}</b><small>{b.author}</small></td><td>{b.isbn}</td><td>{categories.find(c=>c.id===b.categoryId)?.name||'—'}</td><td>{b.quantity}</td><td><span className={b.availableQuantity?'stock':'stock zero'}>{b.availableQuantity}</span></td><td><Actions edit={()=>{setEdit(b.id);setForm({title:b.title,author:b.author,isbn:b.isbn,categoryId:b.categoryId||'',quantity:b.quantity});setShow(true)}} del={()=>del(b.id)}/></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No books found."/>}</div>{show&&<Modal title={edit?'Edit book':'Add book'} close={()=>setShow(false)}><BookForm form={form} setForm={setForm} categories={categories} submit={submit}/></Modal>}</section>}
function Members({members,refresh,notify}){const [q,setQ]=useState(''),[edit,setEdit]=useState(null),[form,setForm]=useState(emptyMember),[show,setShow]=useState(false);const rows=members.filter(m=>(m.name+' '+m.email+' '+m.phone).toLowerCase().includes(q.toLowerCase()));const submit=async e=>{e.preventDefault();try{if(edit)await api('/members/'+edit,{method:'PUT',body:JSON.stringify(form)});else await api('/members',{method:'POST',body:JSON.stringify(form)});notify(edit?'Member updated':'Member added');setShow(false);setEdit(null);setForm(emptyMember);refresh()}catch(e){notify(e.message,'error')}};const del=async id=>{if(!confirm('Delete this member?'))return;try{await api('/members/'+id,{method:'DELETE'});notify('Member deleted');refresh()}catch(e){notify(e.message,'error')}};return <section><Toolbar q={q} setQ={setQ} action={()=>{setShow(true);setEdit(null);setForm(emptyMember)}} label="Add member"/><div className="tableWrap"><table><thead><tr><th>Member</th><th>Email</th><th>Phone</th><th>Address</th><th></th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td><b>{m.name}</b><small>Member #{m.id}</small></td><td>{m.email||'—'}</td><td>{m.phone||'—'}</td><td>{m.address||'—'}</td><td><Actions edit={()=>{setEdit(m.id);setForm({name:m.name,email:m.email||'',phone:m.phone||'',address:m.address||''});setShow(true)}} del={()=>del(m.id)}/></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No members found."/>}</div>{show&&<Modal title={edit?'Edit member':'Add member'} close={()=>setShow(false)}><MemberForm form={form} setForm={setForm} submit={submit}/></Modal>}</section>}
function Categories({categories,refresh,notify}){const [q,setQ]=useState(''),[edit,setEdit]=useState(null),[name,setName]=useState(''),[show,setShow]=useState(false);const rows=categories.filter(c=>c.name.toLowerCase().includes(q.toLowerCase()));const submit=async e=>{e.preventDefault();try{const body=JSON.stringify({name});if(edit)await api('/categories/'+edit,{method:'PUT',body});else await api('/categories',{method:'POST',body});notify(edit?'Category updated':'Category added');setShow(false);setEdit(null);setName('');refresh()}catch(e){notify(e.message,'error')}};const del=async id=>{if(!confirm('Delete this category?'))return;try{await api('/categories/'+id,{method:'DELETE'});notify('Category deleted');refresh()}catch(e){notify(e.message,'error')}};return <section><Toolbar q={q} setQ={setQ} action={()=>{setShow(true);setEdit(null);setName('')}} label="Add category"/><div className="categoryGrid">{rows.map(c=><div className="catCard" key={c.id}><div className="catIcon"><Tags size={20}/></div><div><b>{c.name}</b><small>Category #{c.id}</small></div><Actions edit={()=>{setEdit(c.id);setName(c.name);setShow(true)}} del={()=>del(c.id)}/></div>)}</div>{!rows.length&&<Empty text="No categories found."/>}{show&&<Modal title={edit?'Edit category':'Add category'} close={()=>setShow(false)}><form onSubmit={submit}><Field label="Category name" value={name} onChange={e=>setName(e.target.value)} required/><button className="primary full">{edit?'Save changes':'Create category'}</button></form></Modal>}</section>}
function Borrowings({books,members,borrowings,refresh,notify}){const [issue,setIssue]=useState(false),[form,setForm]=useState({bookId:'',memberId:'',issueDate:today(),dueDate:'',status:'ISSUED'}),[q,setQ]=useState('');const rows=borrowings.filter(x=>`${x.id} ${x.bookId} ${x.memberId} ${x.status}`.toLowerCase().includes(q.toLowerCase()));const submit=async e=>{e.preventDefault();try{await api('/borrowings/issue',{method:'POST',body:JSON.stringify({...form,bookId:Number(form.bookId),memberId:Number(form.memberId)})});notify('Book issued successfully');setIssue(false);setForm({bookId:'',memberId:'',issueDate:today(),dueDate:'',status:'ISSUED'});refresh()}catch(e){notify(e.message,'error')}};const ret=async id=>{if(!confirm('Return this book?'))return;try{await api('/borrowings/return/'+id,{method:'PUT'});notify('Book returned');refresh()}catch(e){notify(e.message,'error')}};return <section><Toolbar q={q} setQ={setQ} action={()=>setIssue(true)} label="Issue book"/><div className="tableWrap"><table><thead><tr><th>ID</th><th>Book</th><th>Member</th><th>Issue date</th><th>Due date</th><th>Status</th><th>Fine</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>#{x.id}</td><td><b>{books.find(b=>b.id===x.bookId)?.title||`Book #${x.bookId}`}</b></td><td>{members.find(m=>m.id===x.memberId)?.name||`Member #${x.memberId}`}</td><td>{x.issueDate}</td><td>{x.dueDate}</td><td><Status value={x.status}/></td><td>₹{Number(x.fine||0).toFixed(2)}</td><td>{x.status==='ISSUED'&&<button className="returnBtn" onClick={()=>ret(x.id)}><RotateCcw size={15}/> Return</button>}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No borrowing records found."/>}</div>{issue&&<Modal title="Issue a book" close={()=>setIssue(false)}><form onSubmit={submit}><Field label="Book" type="select" value={form.bookId} onChange={e=>setForm({...form,bookId:e.target.value})} required options={[['','Select available book'],...books.filter(b=>b.availableQuantity>0).map(b=>[b.id,`${b.title} (${b.availableQuantity} available)`])]}/><Field label="Member" type="select" value={form.memberId} onChange={e=>setForm({...form,memberId:e.target.value})} required options={[['','Select member'],...members.map(m=>[m.id,m.name])]}/><div className="formGrid"><Field label="Issue date" type="date" value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})} required/><Field label="Due date" type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} required/></div><button className="primary full">Issue book</button></form></Modal>}</section>}
function Toolbar({q,setQ,action,label}){return <div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/></div><button className="primary" onClick={action}><Plus size={17}/>{label}</button></div>}
function Field({label,type='text',value,onChange,required,options}){return <label className="field"><span>{label}</span>{type==='select'?<select value={value} onChange={onChange} required={required}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input type={type} value={value} onChange={onChange} required={required}/>}</label>}
function BookForm({form,setForm,categories,submit}){return <form onSubmit={submit}><div className="formGrid"><Field label="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><Field label="Author" value={form.author} onChange={e=>setForm({...form,author:e.target.value})} required/></div><Field label="ISBN" value={form.isbn} onChange={e=>setForm({...form,isbn:e.target.value})} required/><div className="formGrid"><Field label="Category" type="select" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})} options={[['','No category'],...categories.map(c=>[c.id,c.name])]}/><Field label="Quantity" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} required/></div><button className="primary full">Save book</button></form>}
function MemberForm({form,setForm,submit}){return <form onSubmit={submit}><Field label="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><div className="formGrid"><Field label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Field label="Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><button className="primary full">Save member</button></form>}
function Modal({title,close,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><h3>{title}</h3><button onClick={close}><X size={19}/></button></div>{children}</div></div>}
function Actions({edit,del}){return <div className="actions"><button onClick={edit} title="Edit"><Edit3 size={16}/></button><button onClick={del} title="Delete" className="danger"><Trash2 size={16}/></button></div>}
function Status({value}){return <span className={'status '+value.toLowerCase()}>{value}</span>}
function Empty({text}){return <div className="empty">{text}</div>}

createRoot(document.getElementById('root')).render(<App/>);
